### ISSUE TITLE
feat request: add --chunks to zmwfilter

### ISSUE THREAD

**Issue by mrvollger** [PacificBiosciences/pbtk#1]
Hi @armintoepfer,

Not an urgent request by any means, but if you are looking to improve `zmwfilter` I think a great addition would be the `--chunks` argument you have in `actc` and other pacbio commands. Basically:
```
zmwfilter --chunks 2/50 <input.bam>
```
would filter to all the reads in the second chunk of the bam and then stream to stdout. 

This would allow third-party tools (like mine :)) to use the same chucking strategy as you do but without needing to implement our own index reading using pbbam.

Thanks for considering!
Mitchell

**Comment by armintoepfer** [comment]
Please file this again under `pbbioconda` if you are still interested. I'm closing the issues tab here, as only work through https://github.com/PacificBiosciences/pbbioconda/issues
