### ISSUE TITLE
Support for Linux ARM64

### ISSUE THREAD

**Issue by martin-g** [PacificBiosciences/pbtk#3]
Hello,

Would it be possible to provide Linux ARM64 binaries ?
I'd build them myself but I cannot find the source code. I was able to find only Linux x86_64 binaries at https://github.com/PacificBiosciences/pbtk/releases/download/v3.1.0/pbtk.tar.gz

Thank you!

**Comment by armintoepfer** [comment]
We are not planning to release this for ARM yet. We are considering this for future releases
